package fr.lteconsulting.outils;

import java.util.Random;

public class Mots
{
	public static String mot()
	{
		return mots[new Random().nextInt( mots.length )];
	}

	public static String preposition()
	{
		return prepositions[new Random().nextInt( prepositions.length )];
	}

	public static String phrase()
	{
		int nbMots = 3 + new Random().nextInt( 3 );

		String phrase = "";
		for( int i = 0; i < nbMots; i++ )
		{
			if( i > 0 )
				phrase += " " + preposition() + " ";

			phrase += mot();
		}

		phrase = phrase.substring( 0, 1 ).toUpperCase() + phrase.substring( 1 );

		return phrase;
	}

	private static final String[] prepositions = {
			"au",
			"du",
			"de",
			"pour",
			"et",
			"donc",
			",",
			"mais"
	};

	private static final String[] mots = {
			"potager",
			"parc",
			"botanique",
			"kiosque",
			"haie",
			"orangerie",
			"parterre",
			"villa",
			"paradis",
			"square",
			"jardinage",
			"jardinier",
			"roseraie",
			"verger",
			"bosquet",
			"horticulture",
			"pavillon",
			"rocaille",
			"labyrinthe",
			"arbre",
			"Éden",
			"paysagiste",
			"pelouse",
			"tuilerie",
			"acclimatation",
			"arboretum",
			"clôture",
			"fleur",
			"hôtel",
			"palais",
			"promenade",
			"terrasse",
			"zoologique",
			"clos",
			"fruitier",
			"légume",
			"treillage",
			"palmier",
			"salle",
			"zoo",
			"carré",
			"chrysanthème",
			"fontaine",
			"rosier",
			"Versailles",
			"château",
			"galerie",
			"jardin botanique",
			"pergola",
			"tilleul",
			"décoration",
			"hectare",
			"plantation",
			"verdure",
			"arbuste",
			"buis",
			"pépinière",
			"perspective",
			"plante",
			"privé",
			"serre",
			"Babylone",
			"cloître",
			"enclos",
			"haha",
			"jardinerie",
			"patio",
			"paysage",
			"quartier",
			"résidence",
			"brouette",
			"cascade",
			"délice",
			"gazon",
			"horticulteur",
			"porte-fenêtre",
			"treille",
			"allée",
			"appartement",
			"chèvrefeuille",
			"escalier",
			"Ève",
			"gravier",
			"jardinière",
			"lilas",
			"logis",
			"maisonnette",
			"paysager",
			"vert",
			"visiteur",
			"Alhambra",
			"balcon",
			"bâtiment",
			"exotique",
			"floraison",
			"fossé",
			"Hespérides",
			"Jussieu",
			"maraîcher",
			"agrément",
			"arrosage",
			"botaniste",
			"compost",
			"entourer",
			"épouvantail",
			"horticole",
			"jardinet",
			"mare",
			"prairie",
			"rez-de-jardin",
			"rigole",
			"ancolie",
			"emplacement",
			"Épicure",
			"espalier",
			"hortus",
			"Kew",
			"magnifique",
			"massif",
			"ménagerie",
			"oranger",
			"tonnelle",
			"Adam",
			"architecte",
			"balsamine",
			"banc",
			"Barnum",
			"Buffon",
			"cabinet",
			"carrousel",
			"cinéraire",
			"colchique",
			"cyprès",
			"dessin",
			"fierté",
			"grotte",
			"monument",
			"Ninive",
			"orchidée",
			"plate-bande",
			"superbe",
			"bassin",
			"belvédère",
			"chou",
			"cultivé",
			"Daubenton",
			"Diane",
			"folie",
			"Gardens",
			"majestueux",
			"obélisque",
			"œillet",
			"ornement",
			"palmeraie",
			"perron",
			"planté",
			"presbytère",
			"senteur",
			"séquoia",
			"vaste",
			"carreau",
			"cèdre",
			"champêtre",
			"esplanade",
			"étang",
			"fauvette",
			"garden",
			"grimpant",
			"intendant",
			"Jardin remarquable",
			"Leyde",
			"Louvre",
			"Luxembourg",
			"marronnier",
			"muséum",
			"naturel",
			"ombrage",
			"Palais-Royal",
			"topiaire",
			"Trianon",
			"Vaux-le-Vicomte",
			"véranda",
			"André Le Nôtre",
			"apothicaire",
			"avenu",
			"Boulogne",
			"courtilière",
			"dahlia",
			"Duchêne",
			"embellissement",
			"figuier",
			"Fröbel",
			"garden-party",
			"gloriette",
			"hortensia",
			"jardin à la française",
			"Kassapa",
			"Massey",
			"Médicis",
			"ombragé",
			"ornementale",
			"pamplemousse",
			"pré",
			"public",
			"ruelle",
			"terrain",
			"vestige",
			"ville",
			"aurone",
			"bégonia",
			"campanule",
			"charmille",
			"colonnade",
			"conifère",
			"coronille",
			"Cytise",
			"demi-lune",
			"entretien",
			"grand",
			"hamac",
			"Héraclès",
			"herbier",
			"jonquille",
			"Mahal",
			"maison",
			"maraîchage",
			"occuper",
			"plant",
			"portique",
			"posséder",
			"privatif",
			"remarquable",
			"saut-de-loup",
			"Tarbes",
			"vertugadin",
			"Botánico",
			"guaranís",
			"zarzuela" };
}
